---
- name: Install dependencies
  apt: name={{item}} state=present
  with_items:
    - nginx
  notify: restart nginx

- name: Generate DH
  command: openssl dhparam -out dhparam.pem 4096 chdir=/etc/ssl/private/ creates=/etc/ssl/private/dhparam.pem
  register: gen_dh

- name: Change privileges DH
  file: path=/etc/ssl/private/dhparam.pem mode=0400 owner=root group=root
  when: gen_dh|skipped

- name: Remove files without ordernumber
  file: path=/etc/nginx/{{item}}/default state=absent
  with_items:
    - sites-available
    - sites-enabled

- name: Configure default server
  template: src=nginx.conf dest=/etc/nginx/sites-available/00-default owner=root mode=644
  notify: reload nginx

- name: Enable sites
  file: src=/etc/nginx/sites-available/00-default dest=/etc/nginx/sites-enabled/00-default state=link

- name: Configure default server
  template: src=location.conf dest=/etc/nginx/conf.d/00-default-dir-00-default owner=root mode=644

- name: Enable service
  service: name=nginx enabled=yes
