---
# Portforwarinding on the WIRT (1. rule to get all VMs give internet access)
# iptables -t nat -A POSTROUTING -o $FORWORD_INTERFACE -j MASQUERADE
# iptables -t nat -A PREROUTING -p tcp -i $FORWORD_INTERFACE --dport 80 -j DNAT --to-destination 172.18.0.11:80
# iptables -A FORWARD -p tcp -d 172.18.0.11 --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
# iptables -t nat -A PREROUTING -p tcp -i $FORWORD_INTERFACE --dport 80 -j DNAT --to-destination 172.18.0.11:443
# iptables -A FORWARD -p tcp -d 172.18.0.11 --dport 443 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

- hosts: webserver
  roles:
    - nginx
    - letsencrypt
